apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: iz3b3zu2z-nodejs
  janus-idp.io/tekton: iz3b3zu2z-nodejs
  backstage.io/kubernetes-id: iz3b3zu2z-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iz3b3zu2z-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
